### ISSUE TITLE
Trying to share view locals when `view` is undefined

### ISSUE THREAD

**Issue by henrikgundersen** [adonisjs/adonis-shield#10]
The Shield-middleware is tying to share locals to the view, even if Adonis is installed with the `--api-only` flag. This causes an error like this:
```
Cannot read property 'share' of undefined
```

This is because `view` is undefined when Adonis is installed with `--api-only`.

The source of the problem is in `src/Shield/index.js` [line 374](https://github.com/adonisjs/adonis-shield/blob/a6a059c0388ee7137edf22b627876d20102c57a9/src/Shield/index.js#L374) and [line 405](https://github.com/adonisjs/adonis-shield/blob/a6a059c0388ee7137edf22b627876d20102c57a9/src/Shield/index.js#L405)

An `if (view)` statement around the two function calls works as expected, but haven't made a PR because I'm new to adonis and don't want to mess with the code without a deeper understanding first.

Happy to hear your thoughts.

## Package version
`v1.0.8`

## Node.js and npm version
- Node: `v10.15.3`
- NPM:  `v6.9.0`

**Comment by RomainLanz** [comment]
Hey @henrikgundersen! 👋 

Quick question, why do you want to use the Shield Provider for an API?

As state in the readme, this Provider is only useful for SSR application.

**Comment by henrikgundersen** [comment]
Hey @RomainLanz! 👋
The most likely usecase is where you want to opt out of using the integrated Edge templating engine in favor of something else, like Nuxt or React SSR. In some hypothetical case devs would then want to submit `<form>`s and then use Shield Providers CSRF-token for security. 

I know we can use Adonis as a pure API with every front-end/templating framework, but I figured some devs still want the option of just using `<form>`-actions securely  🙂

**Comment by RomainLanz** [comment]
If you believe this is a correct use-case I'd be happy to accept a PR.
The change is quite simple, you need to use the `with` method of the IoC container.

Example here: https://github.com/RomainLanz/adonis-guard/blob/develop/providers/GuardProvider.js#L77

**Comment by thetutlage** [comment]
Closing, since PR has been generated so far and I personally don't think of this feature as needed by majority of users
