### ISSUE TITLE
500 with api only app

### ISSUE THREAD

**Issue by 1001v** [adonisjs/adonis-shield#6]
Hello. Line 374
`this.shareCspViewLocals(headers, view)`
and line 405
`this.shareCsrfViewLocals(newCsrfToken, view)`
in adonis-shield/src/Shield/index.js would fire an expection during http lifecycle with view = undefined (in SPA app with no view engine, for example). Probably you should include some check-up for view var condition. Thank you.

**Comment by thetutlage** [comment]
Can u share the reason, why you want to use `CSP` for an API?

**Comment by 1001v** [comment]
@thetutlage, my point mostly refers to csrf protection, i think ajax request still need it. Anyway, i've included csp line as i think that no crash should happen in app, no matter if there is reason to turn on some options. Thanks.

**Comment by thetutlage** [comment]
Yes it should crash but there is no point in using CSRF or either CSP with API servers.

**Comment by 1001v** [comment]
@thetutlage, i have a single page, not just api.

**Comment by thetutlage** [comment]
How will set you the CSRF token?

**Comment by 1001v** [comment]
@thetutlage, by response.download('index.html')

**Comment by RomainLanz** [comment]
Sorry, but we don't get what you are trying to achieve.

If you have a single page application it means that you have only an API with Adonis.

**Comment by 1001v** [comment]
CSRF should protect form actions of my original site, isn't it? If there's a fake no-ajax form on another site, the only defence would be x-requested-with header when i perfom request.ajax() check in action.
About `response.download('index.html')`: of course this code itself doesn't set any csrf token, but if i have adonis shield middleware, cookie would be set with index.html response, and then angular, for example, will use this cookie automaticaly during http request.

**Comment by RomainLanz** [comment]
Since you'll need to authenticate each request you do with a JWT there's no need to protect yourself against CSRF attack.

**Comment by 1001v** [comment]
> Since you'll need to authenticate each request you'll do with a JWT there's no need to protect yourself against CSRF attack.
I don't use JWT, my auth works with request to an old ipb forum app.

> Also, the CSRF Token is regenerated so the one you receive from index.html will not be available forever + let's say your API will be used by a mobile application or a server-side application you'll not be able to get the token.
I'd like to have my csrf-cookie sessionaly life-time (my other issue thread in this repo is about this btw). New session means that you get new csrf token every time you request for index.html, so there's no problem here.

**Comment by 1001v** [comment]
I don't get it, is this kind of language barrier? Why would you include [line about angularjs in docs](http://adonisjs.com/docs/4.0/csrf#_how_it_works), if you say that where's no need to protect ajax request to adonis?

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by matheuslk** [comment]
how do i use ADONIS JS API and REACT SPA with csrf token GOD
