### ISSUE TITLE
Impossible to set a session XSRF-TOKEN

### ISSUE THREAD

**Issue by 1001v** [adonisjs/adonis-shield#7]
Hello. If i'm right, the [npm cookie documentation says](https://www.npmjs.com/package/cookie#options-1), that excluding such parameters as maxAge and expires from options would make cookie sessional, but the XSRF-TOKEN remains expiring in 3 hours from setting. My options in config/shield.js:csrf.cookieOptions are  
```
{
      httpOnly: false,
      sameSite: true,
      path: '/'
}
```
Thank you.

**Comment by thetutlage** [comment]
You must defined `maxAge: null`. Since internally module merges your config with the default config and removing the key will use the default one.

```js
{
      httpOnly: false,
      sameSite: true,
      path: '/',
      maxAge: null
}
```

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
